# Application Name
spring.application.name=spring-learn


# Port required in the exercise
server.port=8083


# Spring Framework Logging
logging.level.org.springframework=info


# Application Logging
logging.level.com.cognizant.springlearn=debug


# Console Pattern
logging.pattern.console=%d{yyMMdd}|%d{HH:mm:ss.SSS}|%-20.20thread|%5p|%-25.25logger{25}|%25M|%m%n
